defaults: &defaults
  host: localhost
  port: 3306
  adapter: mysql2
  username: videocache
  password: videocache
  encoding: utf8
  timeout: 5000
  pool: 100

development:
  <<: *defaults
  database: cache_dev

production:
  <<: *defaults
  database: cache_prod

test:
  <<: *defaults
  database: cache_test
