development:
  raise_errors: false
  dump_errors: false
  logging: true
  methodoverride: true
  static: true
  public_folder: public
  run: true
  port: 4567
  sessions: true
  layout: :layout

production:
  raise_errors: false
  dump_errors: false
  logging: true
  methodoverride: true
  static: true
  public_folder: public
  run: true
  port: 4567
  sessions: true
  layout: :layout

test:
  dump_errors: false
  methodoverride: true
  static: true
  public_folder: public
  port: 4567
  sessions: true
  layout: :layout
  raise_errors: true
  logging: false
  run: false
