#!/usr/bin/env ruby

require File.expand_path('../../config/application', __FILE__)
require File.expand_path('../../plugin/videocache', __FILE__)
require 'irb'

module IRB # :nodoc:
  def self.start_session(binding)
    unless @__initialized
      args = ARGV
      ARGV.replace(ARGV.dup)
      IRB.setup(nil)
      ARGV.replace(args)
      @__initialized = true
    end
    irb = Irb.new(WorkSpace.new(binding))

    @CONF[:IRB_RC].call(irb.context) if @CONF[:IRB_RC]
    @CONF[:MAIN_CONTEXT] = irb.context

    catch(:IRB_EXIT) do
      irb.eval_input
    end
  end
end

if __FILE__ == $0
  App.connect
  IRB.start_session(binding)
end
