#!/usr/bin/env ruby
#
# (C) Copyright Kulbir Saini <saini@saini.co.in>
# Product Website : http://cachevideos.com/
#

require File.expand_path('../../webapp/webapp', __FILE__)

WebApp::Application.run! if __FILE__ == $0
